# Generated by Django 4.2.4 on 2023-08-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_employee_registraion'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('companyname', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('expiredate', models.DateField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
