# Generated by Django 4.2.4 on 2023-08-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_fileupload_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fileupload',
            new_name='upload',
        ),
    ]
